---
- name: Install and customize the Apache server on Virtual Machines
  hosts: application_servers
  gather_facts: true
  become: true
  vars_files:
    - secrets/db_password.yml
    - ["variables/{{ ansible_facts['os_family'] }}.yml", "variables/debian.yml"]

  tasks:
    - debug:
        msg: Operating System of this box is "{{ ansible_facts['os_family'] }}"

    - name: Ensure Apache is installed
      yum:
        name: "{{ apache_service_name }}"
        state: present

    - name: Ensure Apache is running and starts at boot
      service: name="{{ apache_service_name }}" state=started enabled=true

    - name: Copy customized index.html page
      copy:
        src: custom/index.html
        dest: "{{ path_to_index_file }}"

    - name: Ensure Apache is restarted after the default index.html overridden
      service: name="{{ apache_service_name }}" state=restarted
      notify:
        - Print out the message when the box has changed

    # The following task is just an example of how to set the environment
    # variables and print out the values of decrypted secrets
    - name: Register the decrypted DB password
      shell: echo $DB_PASSWORD
      environment:
        DB_PASSWORD: "{{ db_password }}"
      register: printed_out_db_password

    - name: Print out the decrypted DB password
      debug: var=printed_out_db_password.stdout

  handlers:
    - name: Print out the message when the box has changed
      debug:
        msg:
          - "Sometimes you want a task to run only when a change is made on a machine. For example, you may want to restart a service if a task updates the configuration of that service, but not if the configuration is unchanged. "
          - "Link to handlers page explained --> https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html"
