---
- name: Install and customize the Apache server on CentOS VM
  hosts: app
  gather_facts: true
  become: true

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
    
    - name: Ensure Apache is running and starts at boot
      service: name=httpd state=started enabled=true