---
- name: Install and customize the Apache server on CentOS VM
  hosts: application_servers
  gather_facts: true
  become: true
  vars_files:
    - [ "variables/{{ ansible_facts['os_family'] }}.yml", "variables/debian.yml" ]

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: "{{ apache_service_name }}"
        state: present
    
    - name: Ensure Apache is running and starts at boot
      service: name="{{ apache_service_name }}" state=started enabled=true

    - name: Copy customized index.html page
      copy:
        src: custom/index.html
        dest: "{{ path_to_index_file }}"
    
    - name: Ensure Apache is restarted after the default index.html overridden
      service: name="{{ apache_service_name }}" state=restarted